USE [master]
GO

/****** Object:  Database [Test_Db]    Script Date: 2021-08-07 8:54:01 PM ******/
DROP DATABASE [Test_Db]
GO

/****** Object:  Database [Test_Db]    Script Date: 2021-08-07 8:54:01 PM ******/
CREATE DATABASE [Test_Db]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Test_Db', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Test_Db.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Test_Db_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Test_Db_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Test_Db].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Test_Db] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Test_Db] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Test_Db] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Test_Db] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Test_Db] SET ARITHABORT OFF 
GO

ALTER DATABASE [Test_Db] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Test_Db] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Test_Db] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Test_Db] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Test_Db] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Test_Db] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Test_Db] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Test_Db] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Test_Db] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Test_Db] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Test_Db] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Test_Db] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Test_Db] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Test_Db] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Test_Db] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Test_Db] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Test_Db] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Test_Db] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Test_Db] SET  MULTI_USER 
GO

ALTER DATABASE [Test_Db] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Test_Db] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Test_Db] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Test_Db] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Test_Db] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Test_Db] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Test_Db] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Test_Db] SET  READ_WRITE 
GO


